// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfPAzQPD1JQjqWQ34cnNML3YLwB6uTWXc',
    appId: '1:72169703437:web:458c320011f6f0bc596d44',
    messagingSenderId: '72169703437',
    projectId: 'ieee-69f18',
    authDomain: 'ieee-69f18.firebaseapp.com',
    storageBucket: 'ieee-69f18.firebasestorage.app',
    measurementId: 'G-Q4LZJ6T926',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyNSbde1YH-eV0p_WwsTbadP-8D3RSiAc',
    appId: '1:72169703437:android:03f01a55f852821a596d44',
    messagingSenderId: '72169703437',
    projectId: 'ieee-69f18',
    storageBucket: 'ieee-69f18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBPRPbjk7uAdnJfNZ-87pHT0TGSrAF14',
    appId: '1:72169703437:ios:4c3cc06538dd6d9b596d44',
    messagingSenderId: '72169703437',
    projectId: 'ieee-69f18',
    storageBucket: 'ieee-69f18.firebasestorage.app',
    iosBundleId: 'com.example.ieee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABBPRPbjk7uAdnJfNZ-87pHT0TGSrAF14',
    appId: '1:72169703437:ios:4c3cc06538dd6d9b596d44',
    messagingSenderId: '72169703437',
    projectId: 'ieee-69f18',
    storageBucket: 'ieee-69f18.firebasestorage.app',
    iosBundleId: 'com.example.ieee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfPAzQPD1JQjqWQ34cnNML3YLwB6uTWXc',
    appId: '1:72169703437:web:2b560178f2ba0ba5596d44',
    messagingSenderId: '72169703437',
    projectId: 'ieee-69f18',
    authDomain: 'ieee-69f18.firebaseapp.com',
    storageBucket: 'ieee-69f18.firebasestorage.app',
    measurementId: 'G-GY4KCX1VSP',
  );
}
